version: "3.7"

services:
  svc:
    build:
      context: .
      dockerfile: deployments/svc-systemd/Dockerfile
    environment:
      - GRPC_ADDRESS=${GRPC_ADDRESS} 
      - GRPC_PORT=${GRPC_PORT}
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - restartnet
    depends_on:
      - gw
  gw:
    container_name: ${GRPC_ADDRESS}
    build:
      context: .
      dockerfile: deployments/gw/Dockerfile
    ports:
      - "${GW_PORT}:${GW_PORT}"
      - "${GRPC_PORT}"
    environment: 
      - GRPC_PORT=${GRPC_PORT}
      - GW_PORT=${GW_PORT}
    networks:
      - restartnet
networks:
  restartnet:
